name: Validate code
on: pull_request
jobs:
  validate-code:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  build:
    runs-on: ${{ matrix.os }}
    needs: validate-code
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run:  |
          npm ci
          npm ci --prefix=examples/basic
          npm ci --prefix=examples/advanced
          npm ci --prefix=examples/kopytko-cli
      - name: Run build basic
        run: npm run build --prefix=examples/basic
      - name: Run build advanced
        run: npm run build --prefix=examples/advanced -- test
      - name: Run build kopytko-cli
        run: npm run build --prefix=examples/kopytko-cli -- test


